isProd: false

server:
  port: 8081

my:
  swagger:
    prefix:

spring:
  application:
    name: data-catalogue
  datasource:
    url: jdbc:postgresql://ec2-54-170-100-209.eu-west-1.compute.amazonaws.com:5432/d77219cj169g7e
    username: zgfppzhhtvttao
    password: ac6af20e8211130cafd980cd7f78098e7dc85d6a03e46491b73a4f8e2e67d32c
    driverClassName: org.postgresql.Driver
    initialize: true
    initialization-mode: always
    hikari:
      connectionTimeout: 200000
      maximumPoolSize: 10
      idle-timeout: 300000
      minimum-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        bootstrap_mode: default
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: true

feign:
  httpclient:
    connection-timeout: 60000
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: prod

my:
  swagger:
    prefix: /data-catalogue

isProd: true