isProd: ${IS_PROD:false}

server:
  port: ${PORT:8081}

spring:
  application:
    name: data-catalogue
  cloud:
    consul:
      host: consul.service.consul

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true