isProd: false

server:
  port: 8081

spring:
  application:
    name: data-catalogue
  cloud:
    consul:
      host: localhost
      config:
        fail-fast: false
        format: yaml
      discovery:
        fail-fast: false
        prefer-ip-address: true

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true