apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalogue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-catalogue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-catalogue
    spec:
      containers:
        - image: blarc/rso-data-catalogue:latest
          name: data-catalogue
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: data-catalogue
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: data-catalogue